[package]
name = "matrix-github"
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version="1", features=["serde-json"]}
napi-derive = "1"
url = "2"
serde_json = "1"
serde = "1"
serde_derive = "*"

[build-dependencies]
napi-build = "1"