# This is an example configuration file

bridge:
  # Basic homeserver configuration
  #
  domain: example.com
  url: http://localhost:8008
  mediaUrl: http://example.com
  port: 9993
  bindAddress: 127.0.0.1
github:
  installationId: 6854059
  auth:
    id: 123
    privateKeyFile: github-key.pem
  oauth:
    client_id: foo
    client_secret: bar
    redirect_uri: https://example.com/bridge_oauth/
  webhook:
    secret: secrettoken
gitlab:
  instances:
    gitlab.com:
      url: https://gitlab.com
  webhook:
    secret: secrettoken
webhook:
  port: 9000
  bindAddress: 0.0.0.0
passFile: passkey.pem
queue:
  monolithic: true
  port: 6379
  host: localhost
logging:
  level: info

sdasdsade